; Installer configuration file for automated setup.

[metadata]
osname=windows


[installerParamaters]
installDirectory=C:\Program Files\Prismonian\ProxyStop-Server
silent=true
auto_start_after_install=false
checkDependencies=true
auto_install_dependencies=false
install_stock_fingerprints=true
stock_fingerprints_uri=https://cdn.prismonian.com/applications/proxystop-server/depend/stock-fingerprints.zip?
deleteArtifacts=true
customWindowsPermissions=true
requiresSudo = false
auto_run_npm_install=true

[paramaters]
foldername=fingerprints
support_management_server=false
autoUpdate=false
customWindowsPermissions=true
port=10225

[scripts]
scripts-uri=https://cdn.prismonian.com/applications/proxystop-server/depend/extra-scripts/
fingerprint_generator=fingerprint_generator.js
processor=processor.js ;This is a required dependency. If you delete this, this will stop working! DONT TOUCH!